COMMAND_COOLDOWN = 2  # seconds

NL = "\n"

CODE_BLOCK_FMT = "```\n%s\n```"

MESSAGE_CHAR_LIMIT = 1900
EMBED_DESC_CHAR_LIMIT = 4096
EMBED_FIELD_CHAR_LIMIT = 1024

LOG_BORDER_LENGTH = 50
LOG_BORDER = "-" * LOG_BORDER_LENGTH

PREFIX = "!!"

INDENT = (" \u200b") * 4

HEAD = [
            ":grinning:",
            ":smiley:",
            ":smile:",
            ":grin:",
            ":laughing:",
            ":star_struck:",
            ":sweat_smile:",
            ":joy:",
            ":rofl:",
            ":relieved:",
            ":blush:",
            ":innocent:",
            ":slight_smile:",
            ":upside_down:",
            ":wink:",
            ":relieved:",
            ":heart_eyes:",
            ":kissing_heart:",
            ":kissing:",
            ":kissing_smiling_eyes:",
            ":kissing_closed_eyes:",
            ":yum:",
            ":zany_face:",
            ":stuck_out_tongue_winking_eye:",
            ":stuck_out_tongue_closed_eyes:",
            ":stuck_out_tongue:",
            ":money_mouth:",
            ":hugging:",
            ":nerd:",
            ":sunglasses:",
            ":clown:",
            ":cowboy:",
            ":smirk:",
            ":unamused:",
            ":disappointed:",
            ":pensive:",
            ":worried:",
            ":confused:",
            ":slight_frown:",
            ":frowning2:",
            ":persevere:",
            ":confounded:",
            ":tired_face:",
            ":weary:",
            ":triumph:",
            ":rage:",
            ":face_with_symbols_over_mouth:",
            ":woman_gesturing_no:",
            ":no_mouth:",
            ":neutral_face:",
            ":expressionless:",
            ":hushed:",
            ":frowning:",
            ":anguished:",
            ":open_mouth:",
            ":dizzy_face:",
            ":exploding_head:",
            ":flushed:",
            ":scream:",
            ":fearful:",
            ":baby:",
            ":child:",
            ":boy:",
            ":girl:",
            ":adult:",
            ":man:",
            ":woman:",
            ":bearded_person:",
            ":bearded_person:",
            ":bearded_person:",
            ":adult:",
            ":man_red_haired:",
            ":woman_red_haired:",
            ":adult:",
            ":man_curly_haired:",
            ":woman_curly_haired:",
            ":adult:",
            ":man_white_haired:",
            ":woman_white_haired:",
            ":adult:",
            ":man_bald:",
            ":woman_bald:",
            ":blond_haired_person:",
            ":blond_haired_man:",
            ":blond_haired_woman:",
            ":older_adult:",
            ":older_man:",
            ":older_woman:",
            ":smiling_imp:",
            ":imp:",
            ":skull:",
            ":skull_crossbones:",
            ":poop:",
            ":clown:",
            ":japanese_ogre:",
            ":japanese_goblin:",
            ":ghost:",
            ":alien:",
            ":space_invader:",
            ":robot:",
            ":smiley_cat:",
            ":smile_cat:",
            ":joy_cat:",
            ":heart_eyes_cat:",
            ":smirk_cat:",
            ":kissing_cat:",
            ":scream_cat:",
            ":crying_cat_face:",
            ":pouting_cat:",
            ":monkey_face:",
            ":gorilla:",
            ":dog:",
            ":wolf:",
            ":fox:",
            ":raccoon:",
            ":cat:",
            ":lion_face:",
            ":tiger:",
            ":cow:",
            ":pig:",
            ":boar:",
            ":mouse:",
            ":hamster:",
            ":rabbit:",
            ":bear:",
            ":polar_bear:",
            ":koala:",
            ":panda_face:",
            ":chicken:",
            ":eagle:",
            ":egg:",
            ":frog:",
            ":new_moon_with_face:",
            ":full_moon_with_face:",
            ":sun_with_face:",
            ":jack_o_lantern:",
        ]

BODY = [
            ":koko:",
            ":sa:",
            ":u6708:",
            ":u6709:",
            ":u6307:",
            ":ideograph_advantage:",
            ":u5272:",
            ":accept:",
            ":u7981:",
            ":u5408:",
            ":u7a7a:",
            ":u55b6:",
            ":u6e80:",
            ":u7121:",
            ":u6708:",
            ":u7533:",
            ":red_circle:",
            ":orange_circle:",
            ":yellow_circle:",
            ":green_circle:",
            ":blue_circle:",
            ":purple_circle:",
            ":brown_circle:",
            ":black_circle",
            ":soccer:",
            ":baseball:",
            ":softball:",
            ":basketball:",
            ":volleyball:",
            ":heart:",
            ":orange_heart:",
            ":yellow_heart:",
            ":green_heart:",
            ":blue_heart:",
            ":purple_heart:",
            ":brown_heart:",
            ":black_heart:",
            ":white_heart:",
            ":heart_on_fire:",
            ":mending_heart:",
            ":new_moon:",
            ":first_quarter_moon:",
            ":waxing_gibbous_moon:",
            ":waning_gibbous_moon:",
            ":last_quarter_moon:",
            ":lab_coat:",
            ":safety_vest:",
            ":necktie:",
            ":shirt:",
            ":dress:",
            ":one_piece_swimsuit:",
            ":bikini:",
            ":womans_clothes:",
            ":musical_keyboard:",
            ":atom:",
            ":infinity:",
            ":peace:",
            ":name_badge:",
            ":o:",
            ":eight_spoked_asterisk:",
            ":radioactive:",
            ":biohazard:",
            ":8ball:",
            ":cookie:",
            ":rice_cracker:",
            ":rice_ball:",
            ":apple:",
            ":green_apple:",
            ":radio_button:",
            ":white_square_button:",
            ":peach:",
            ":tomato:",
            ":star2:",
            ":chestnut:",
            ":gem:",
            ":red_square:",
            ":orange_square:",
            ":yellow_square:",
            ":green_square:",
            ":blue_square:",
            ":purple_square:",
            ":brown_square:",
]

ANSWERS = [
        "infinite games but no bacon",
        "no games, no bacon",
        "infinite games, no games, but some games, and some bacon on the side",
        "games, games, oh so many games, but no bacon",
        "infinite games but also an uncountably infinite amount of games",
        "no bacon but some games",
        "some games but also some more games with some bacon",
        "unlimited games but only with bacon",
        "no games but with some games and infinite bacon",
        "only just one game to your lineage",
        "negative bacon",
        "negative games",
        "infinite negative bacon with infinite games",
        "3 bacon",
        "17 games",
        "baconless games forever",
        "gameless bacon feast",
        "games galore, but bacon no more",
        "a bacon-free game extravaganza",
        "endless games, but bacon's amiss",
        "a touch of games, sans bacon",
        "unlimited bacon, limited games",
        "games without bacon, a peculiar twist",
        "baconless entertainment, boundless games",
        "the great game-bacon paradox",
        "games aplenty, yet bacon is scarce",
        "no games, all bacon, a unique trade",
        "game overload, baconless delight",
        "a bacon-driven game marathon",
        "games abound, bacon eludes",
        "bacon famine, game feast",
        "a never-ending game buffet without bacon",
        "baconless challenges, game-filled days",
        "the eternal quest for games and bacon",
        "bacon's absence, games' abundance",
        "a baconless gameverse",
        "endless bacon chase, limited games",
        "the enigma of games and the missing bacon",
        "games without borders, baconless horizons",
        "bacon's vanishing act, games persist",
        "a world of games, a shortage of bacon",
        "bacon withdrawal, game immersion",
        "games multiply, bacon diminishes",
        "the bacon paradox in a world of games",
        "games galore, bacon no more",
        "bacon deprivation, game addiction",
        "games unlimited, bacon on the wane",
        "a game-filled universe, devoid of bacon",
        "the grand game-bacon experiment",
        "baconless battles, game conquests",
        "games transcend, bacon recedes",
        "bacon scarcity, game abundance",
        "a game trove, a baconless reality",
        "the allure of games, the absence of bacon",
        "baconless adventures in a realm of games",
        "games unbounded, bacon forgotten",
        "the vanishing bacon conundrum",
        "the infinite game spectrum, bacon excluded",
        "bacon eludes, games endure",
        "games flourish, bacon dwindles",
        "bacon shortage, game abundance",
        "a realm bereft of bacon, teeming with games",
        "the game-bacon duality, in perpetual balance",
        "bacon's absence, games' ubiquity",
        "games without bacon, a realm extraordinary",
        "bacon's scarcity, games' abundance persists",
        "a world of games, a dearth of bacon",
        "baconless quests, game-filled odysseys",
        "games multiply, bacon diminishes endlessly",
        "the bacon enigma, the allure of games",
        "game haven, baconless paradise",
        "bacon's scarcity, games' overflow",
        "a game-filled universe, devoid of bacon's taste",
        "the grand experiment of game and bacon",
        "baconless battles, game conquests without end",
        "games unbounded, bacon forgotten",
        "the elusive bacon, the enduring game",
        "bacon scarcity, game abundance without respite",
        "a realm bereft of bacon, teeming with ceaseless games",
        "the game-bacon duality, in perpetual equilibrium",
        "bacon eludes, games endure relentlessly",
        "games flourish, bacon dwindles persistently",
        "bacon shortage, game abundance prevails",
        "a realm without bacon, a world of games forever",
        "baconless quests, game-filled odysseys unending",
        "games multiply, bacon diminishes endlessly",
        "the bacon enigma, the labyrinth of games unending",
        "game haven, baconless paradise eternal",
        "bacon-starved game enthusiasts unite forever",
        "games overflow, bacon retreats eternally",
        "bacon's scarcity, games' infinity without end",
        "a game wonderland, bacon forgotten forever",
        "the elusive bacon, the everlasting game unceasing",
        "baconless realms, game-filled realms forever",
        "games in plenty, bacon in want perpetually",
        "bacon's scarcity, games' expanse without bounds",
        "the game's bounty, the bacon's lament eternal",
        "games infinite, bacon finite indefinitely",
        "bacon's scarcity, game abundance prevails perpetually",
        "a world of games, a world without bacon forever",
        "baconless challenges, game-filled",
    ]